// Code generated by hertz generator.

package share

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/dgdts/ShareServer/biz/model/share"
	biz_share "github.com/dgdts/ShareServer/biz/share"
	"github.com/dgdts/ShareServer/internal/response"
)

// GetShareNote .
// @router /api/v1/share/note [GET]
func GetShareNote(ctx context.Context, c *app.RequestContext) {
	var req share.GetShareNoteRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.JSONError(c, err)
		return
	}

	shareId := c.Param("share_id")
	if shareId == "" {
		response.JSONError(c, errors.New("share_id is required"))
		return
	}
	req.ShareId = shareId

	html, err := biz_share.GetShareNote(ctx, &req)
	if err != nil {
		response.JSONError(c, err)
		return
	}

	c.Data(consts.StatusOK, "text/html", html)
}

// ListShareNoteComments .
// @router /api/v1/share/note/comments [GET]
func ListShareNoteComments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.ListShareNoteCommentsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.ListShareNoteCommentsResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateShareNoteComment .
// @router /api/v1/share/note/comment [POST]
func CreateShareNoteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.CreateShareNoteCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.CreateShareNoteCommentResponse)

	c.JSON(consts.StatusOK, resp)
}
