// Code generated by hertz generator.

package share

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shareMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _noteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsharenoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsharenotecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsharenotecommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _share_idMw() []app.HandlerFunc {
	// your code...
	return nil
}
